# -*- coding: utf-8 -*-
"""API_Sample_Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gllivvkYa197WQf6wHznWSQXAY8QFGtz
"""

import requests
import pandas as pd
import gspread
from google.colab import auth
from google.auth import default
from gspread_dataframe import set_with_dataframe

# Authenticate Google Sheets
auth.authenticate_user()
creds, _ = default()
gc = gspread.authorize(creds)

def get_and_dump_data():
    # Hitting API and getting Data

    url = "https://api.coingecko.com/api/v3/coins/markets"
    params = {
        'vs_currency': 'usd',
        'order': 'market_cap_desc',
        'per_page': 50,
        'page': 1,
        'sparkline': 'false'
    }

    try:
        response = requests.get(url, params=params)
        response.raise_for_status()
        data = response.json()

        # Create and filter DataFrame

        df = pd.DataFrame(data)
        df = df[['name', 'symbol', 'current_price', 'market_cap', 'total_volume', 'last_updated']]

        # --- Part B: Dump to Google Sheets ---
        spreadsheet_id = "1RZ1_bAxhv4Nannl1v5DsY8Dpu6JmAYY2eC95kUHUeSI"
        spreadsheet = gc.open_by_key(spreadsheet_id)

        # Select worksheet (Ensures "DDS" exists)
        try:
            worksheet = spreadsheet.worksheet("DDS")
        except gspread.exceptions.WorksheetNotFound:
            worksheet = spreadsheet.add_worksheet(title="DDS", rows="1000", cols="20")

        # Clear the sheet before dumping new data (Optional but recommended for clean dumps)
        worksheet.clear()

        # Push the entire DataFrame starting from cell A1
        set_with_dataframe(worksheet, df)

        # Optional: Add your custom names at the very top or specific cells if needed
        # worksheet.update_acell('H1', "Rishab is a good boy")

        print("Success! API data synced to Google Sheets.")

    except Exception as e:
        print(f"Error occurred: {e}")

# Run the function
get_and_dump_data()

